#:import menu menu

MainWidget:

<MainWidget>:
    canvas.before:
        Rectangle:
            size: self.size
            source: 'Resources/images/bg1.jpg'
    menu_widget: menu_widget
    perspectivePointX: self.width/2
    perspectivePointY: self.height * 0.75
    MenuWidget:
        id: menu_widget
    Label:
        text: root.score_text
        font_size: dp(20)
        font_name: 'Resources/fonts/Eurostile.ttf'
        size_hint: 0.3, 0.3
        pos_hint: {"x": 0, "top": 1}